---
# setup/install tasks
- include: setup-rhel{{ ansible_distribution_major_version }}.yml
  when: ansible_os_family == 'RedHat'

- include: setup-darwin.yml
  when: ansible_os_family == 'Darwin'

- include: setup-Ubuntu.yml
  when: ansible_distribution == 'Ubuntu'
